package com.gymsync.model;

public enum MuscleGroup {
    CHEST, BACK, SHOULDERS, BICEPS, TRICEPS, FOREARMS,
    ABS, OBLIQUES, LOWER_BACK,
    QUADRICEPS, HAMSTRINGS, GLUTES, CALVES, ADDUCTORS, ABDUCTORS,
    FULL_BODY, CARDIO
}